name: Docker Image CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
          login-server: divaacr.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
    - run: |
          docker build ./ -t divaacr.azurecr.io/web-app-api:latest
          docker push divaacr.azurecr.io/web-app-api:latest
          
          
